CREATE TABLE CLIENT
(
    ID   IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PROJECT
(
    ID          IDENTITY PRIMARY KEY,
    CLIENT_ID   BIGINT       NOT NULL,
    NAME        VARCHAR(200) NOT NULL,
    START_DATE  DATE         NOT NULL,
    FINISH_DATE DATE         NOT NULL,
    CONSTRAINT FK_PROJECT_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);

CREATE TABLE WORKER
(
    ID       IDENTITY PRIMARY KEY,
    NAME     VARCHAR(100) NOT NULL,
    BIRTHDAY DATE         NOT NULL,
    LEVEL    VARCHAR(20)  NOT NULL,
    SALARY   INT          NOT NULL
);

CREATE TABLE PROJECT_WORKER
(
    PROJECT_ID BIGINT NOT NULL,
    WORKER_ID  BIGINT NOT NULL,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    CONSTRAINT FK_PW_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
    CONSTRAINT FK_PW_WORKER FOREIGN KEY (WORKER_ID) REFERENCES WORKER (ID)
);
